### ISSUE TITLE
Pagination handling example

### ISSUE THREAD

**Issue by Polve** [CrowdStrike/ember-headless-table#241]
In the class list I found something related to pagination but I can't find any example using it so I'm unable to understand how to use it

**Comment by NullVoxPopuli** [comment]
Pagination is handled externally:
You'd do something like this
```hbs
<Data as |d|>
  <YourTable @data={{d.records}} />
  <Pagination @meta={{d.meta}} @onNext={{...}} />
</Data>
```

The pagination interface in this repo was accidentally left in, and isn't actually used, afaik

**Comment by Polve** [comment]
Thanks

in the example above, how can I tell the table that I changed the @data (without triggering a new route)?

**Comment by NullVoxPopuli** [comment]
Why don't you want to trigger a route transition? Generally folks want table state serialized to the URL

**Comment by Polve** [comment]
Because I have several tables inside my page and I want to be able to paginate each one indipendently

**Comment by NullVoxPopuli** [comment]
If you move all data loading for each table into component-land instead of the route, your goal is very doable

**Comment by Polve** [comment]
yes that's my goal, but how do I trigger a table redraw after pressing the pagination buttons?

**Comment by NullVoxPopuli** [comment]
In the example, if records is `@tracked` , and your function for handling page changes updates records, there is nothing for you to do. The framework handles the update 🎉 

I can share a real/runnable example later if you're still stuck

**Comment by Polve** [comment]
Everything works as expected, thanks!
I close this since I overlooked #163 that was already on topic
