### ISSUE TITLE
Content disappears when trying to move a column past a hidden column

### ISSUE THREAD

**Issue by vitch** [CrowdStrike/ember-headless-table#60]
I was just checking out the docs and randomly did the following which resulted in all of the content becoming invisible:

![disappearing content](https://user-images.githubusercontent.com/9898/200544596-74f2413a-e694-4ef3-8b32-3113eab949f7.gif)

**Comment by NullVoxPopuli** [comment]
thanks for reporting!

I've reproduced the issue and am going to work on a fix!
